### ISSUE TITLE
Cannot install torch

### ISSUE THREAD

**Issue by vzakharov** [noyoshi/smart-sketch#12]
When I try to `pip3 install -r requirements.txt`, I get this:
```Collecting torch>=1.0.0 (from -r requirements.txt (line 19))
  Could not find a version that satisfies the requirement torch>=1.0.0 (from -r requirements.txt (line 19)) (from versions: 0.1.2, 0.1.2.post1)
No matching distribution found for torch>=1.0.0 (from -r requirements.txt (line 19))```

Any ideas?

**Comment by vzakharov** [comment]
Perhaps you meant `pytorch`?

**Comment by vzakharov** [comment]
Okay, installed separately via conda. Note that a couple of other modules were also “not found”, namely `dill` and `scipy`

**Comment by ajayyy** [comment]
scipy should exist: https://www.scipy.org

**Comment by vzakharov** [comment]
It does exist, but is not installed automatically (had to run a separate conda isntall for this)
