### ISSUE TITLE
Will instructions be added to readme?

### ISSUE THREAD

**Issue by oblsci** [noyoshi/smart-sketch#5]
This smart-sketch implementation is awesome; any chance you could add instructions to the readme to setup and run the UI?  Thanks!!

**Comment by tinawu-23** [comment]
Thank you :) to use the app you can use the URL http://smartsketch.xyz/; if you're looking for a way to run the UI on your local machine, we'll update the readme with instructions soon!

**Comment by noah-yoshida** [comment]
Hey @oblsci , if you mean the server, I'll add instruction for that soon. But you can't run the UI by iteself right now.

**Comment by oblsci** [comment]
thanks for the update @tinawu-23 @noyoshi can't wait!  really appreciate you pulling this together in first place, so interesting how it works!
